version: '3'

services:
  todoback:
    image: todobackend
    restart: always
    ports:
      - 3001:3001

  todofront:
    depends_on:
      - todoback
    image: todofrontend
    restart: always
    environment:
      - REACT_APP_API_HOST=todoback
    ports:
      - 3000:3000

  todotests:
    depends_on:
      - todoback
      - todofront
    image: todotests
    restart: always
    environment:
      - FRONT_HOST=todofront